{% set name = "cyberpandas" %}
{% set version = "1.1.1" %}
{% set sha256 = "feef0f7ca9e43147e080de805eee1bfb80a44ba5c71d3b344161ff4f0dc45af7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1001
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
  run:
    - python
    - ipaddress  # [py27]
    - setuptools
    - pandas >=0.23.0


test:
  imports:
    - cyberpandas

about:
  home: http://github.com/ContinuumIO/cyberpandas
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Pandas extension array for IP and MAC addresses.'

  # The remaining entries in this section are optional, but recommended
  description: |
    Cyberpandas provides support for storing IP and MAC address data inside a pandas
    DataFrame using pandas' Extension Array Interface.
  doc_url: https://cyberpandas.readthedocs.io/en/latest/
  dev_url: https://github.com/ContinuumIO/cyberpandas

extra:
  recipe-maintainers:
    - TomAugspurger
